SocialGoal/ViewModels/CommentsViewModel.cs
using System;
using SocialGoal.Model.Models;

namespace SocialGoal.Web.ViewModels
{
    public class CommentsViewModel
    {
        public int CommentId { get; set; }

        public string CommentText { get; set; }

        public int UpdateId { get; set; }

        public string UserId { get; set; }

        public DateTime CommentDate { get; set; }

        public ApplicationUser User { get; set; }
    }
}

SocialGoal/ViewModels/FocusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SocialGoal.Model.Models;
using SocialGoal.Web.Core.Models;

namespace SocialGoal.Web.ViewModels
{
    public class FocusViewModel
    {
        public int FocusId { get; set; }

        public string FocusName { get; set; }

        public string Description { get; set; }

        public int GroupId { get; set; }

        public virtual Group Group { get; set; }

        public bool IsAMember { get; set; }

        public virtual IEnumerable<GroupGoalViewModel> GroupGoal { get; set; }

        public virtual IEnumerable<ApplicationUser> Users { get; set; }

    }
}

SocialGoal/ViewModels/FollowingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SocialGoal.Model.Models;

namespace SocialGoal.Web.ViewModels
{
    public class FollowingViewModel
    {
        public string UserId { get; set; }

        public string Email { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string ProfilePicUrl { get; set; }

        public string UserName { get; set; }
    }
}

SocialGoal/ViewModels/GroupGoalViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using SocialGoal.Model.Models;
using System.Web.Mvc;

namespace SocialGoal.Web.ViewModels
{
    public class GroupGoalViewModel
    {
         public int GroupGoalId { get; set; }
       [Required(ErrorMessage = "*")]
        public string GoalName { set; get; }
        [Required(ErrorMessage = "*")]
        public string Description { get; set; }

        [Required(ErrorMessage = "*")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "*")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime EndDate { get; set; }

        public double? Target { get; set; }
        
        public int? MetricId { get; set; }

        public int? FocusId { get; set; }

        public string UserId { get; set; }

        public int GoalStatusId { get; set; }

        public DateTime CreatedDate { get; set; }

        public int GroupUserId { get; set; }

        public int AssignedGroupUserId { get; set; }

        public string AssignedUserId { get; set; }

        public string AssignedTo { get; set; }

        public int GroupId { get; set; }

        public virtual GoalStatus GoalStatus { get; set; }

        public IEnumerable<SelectListItem> GoalStatuses { get; set; }

        public ApplicationUser User { get; set; }

        public virtual GroupUser GroupUser { get; set; }

        public virtual Metric Metric { get; set; }

        public virtual Focus Focus { get; set; }

        public virtual Group Group { get; set; }

        public virtual IEnumerable<GroupUpdate> Updates { get; set; }

        public IEnumerable<ApplicationUser> Users { get; set; }

        public bool IsAMember { get; set; }

        //public GroupGoalViewModel()
        //{
        //    CreatedDate = DateTime.Now;
        //    StartDate = DateTime.Now;
        //    EndDate = DateTime.Now;
        //}
    }
}

SocialGoal/ViewModels/GroupViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using SocialGoal.Model.Models;

namespace SocialGoal.Web.ViewModels
{
    public class GroupViewModel
    {

        public int GroupId { get; set; }

        [Required]
        public string GroupName { get; set; }

        [Required]
        public string Description { get; set; }

        public DateTime CreatedDate { get; set; }

        //public int UserId { get; set; }

        //public int GroupUserId { get; set; }

        public virtual IEnumerable<GroupGoalViewModel> Goals { get; set; }

        public bool IsAMember { get; set; }

        public bool RequestSent { get; set; }

        public bool InvitationSent { get; set; }

        public int NoOfMembers { get; set; }

        public bool Admin { get; set; }

        public virtual IEnumerable<Focus> Focus { get; set; }

        public virtual IEnumerable<GroupGoalViewModel> GoalsAssignedToOthers { get; set; }

        public virtual IEnumerable<GroupGoalViewModel> GoalsAssignedToMe { get; set; }

        //public virtual GroupUser GroupUser { get; set; }

        public IEnumerable<ApplicationUser> Users { get; set; }

    }
}

SocialGoal/ViewModels/MemberViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SocialGoal.Model.Models;

namespace SocialGoal.Web.ViewModels
{
    public class MemberViewModel
    {
        public int GroupId { get; set; }

        public Group Group { get; set; }

        public string UserId { get; set; }

        public int GroupUserId { get; set; }

        public string UserName { get; set; }

        public virtual ApplicationUser User { get; set; }

        //public IEnumerable<GroupUser> GroupUser { get; set; }

        //public IEnumerable<User> Users { get; set; }
    }
}

SocialGoal/ViewModels/UpdateViewModel.cs
using System;
using System.Collections.Generic;
using SocialGoal.Model.Models;
using System.Linq;
using System.Web;

namespace SocialGoal.Web.ViewModels
{
    public class UpdateViewModel
    {
        public int UpdateId { get; set; }

        public string Updatemsg { get; set; }

        public double? status { get; set; }

        public int GoalId { get; set; }

        public DateTime UpdateDate { get; set; }

        public virtual Goal Goal { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

        public bool? IsSupported { get; set; }

        public virtual ICollection<UpdateSupport> UpdateSupports { get; set; }
    }
}

SocialGoal/Controllers/GroupController.cs
using System.Drawing.Drawing2D;
using AutoMapper;
using PagedList;
using SocialGoal.Data.Infrastructure;
using SocialGoal.Model.Models;
using SocialGoal.Service;
using SocialGoal.Web.Core.Models;
using SocialGoal.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialGoal.Web.Core.Extensions;
using SocialGoal.Web.Mailers;
using SocialGoal.Properties;
using Microsoft.AspNet.Identity;

namespace SocialGoal.Web.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private readonly IGroupService groupService;
        private readonly IGroupUserService groupUserService;
        private readonly IMetricService metricService;
        private readonly IFocusService focusService;
        private readonly IGroupGoalService groupGoalService;
        private readonly IUserService userService;
        private readonly IGroupInvitationService groupInvitationService;
        private readonly ISecurityTokenService securityTokenService;
        private readonly IGroupUpdateService groupUpdateService;
        private readonly IGroupCommentService groupCommentService;
        private readonly IGoalStatusService goalStatusService;
        public readonly IGroupRequestService groupRequestService;
        private readonly IFollowUserService followUserService;
        private readonly IGroupCommentUserService groupCommentUserService;
        private readonly IGroupUpdateSupportService groupUpdateSupportService;
        private readonly IGroupUpdateUserService groupUpdateUserService;

        private IUserMailer userMailer = new UserMailer();
        public IUserMailer UserMailer
        {
            get { return userMailer; }
            set { userMailer = value; }
        }

        public GroupController(IGroupService groupService, IGroupUserService groupUserService, IUserService userService, IMetricService metricService, IFocusService focusService, IGroupGoalService groupgoalService, IGroupInvitationService groupInvitationService, ISecurityTokenService securityTokenService, IGroupUpdateService groupUpdateService, IGroupCommentService groupCommentService, IGoalStatusService goalStatusService, IGroupRequestService groupRequestService, IFollowUserService followUserService, IGroupCommentUserService groupCommentUserService, IGroupUpdateSupportService groupUpdateSupportService, IGroupUpdateUserService groupUpdateUserService)
        {
            this.groupService = groupService;
            this.groupInvitationService = groupInvitationService;
            this.userService = userService;
            this.groupUserService = groupUserService;
            this.metricService = metricService;
            this.focusService = focusService;
            this.groupGoalService = groupgoalService; ;
            this.securityTokenService = securityTokenService;
            this.groupUpdateService = groupUpdateService;
            this.groupCommentService = groupCommentService;
            this.goalStatusService = goalStatusService;
            this.groupRequestService = groupRequestService;
            this.followUserService = followUserService;
            this.groupCommentUserService = groupCommentUserService;
            this.groupUpdateSupportService = groupUpdateSupportService;
            this.groupUpdateUserService = groupUpdateUserService;
        }
        //
        // GET: /Group/

        public ViewResult Index(int id)
        {
            GroupViewModel group = Mapper.Map<Group, GroupViewModel>(groupService.GetGroup(id));
            group.Goals = Mapper.Map<IEnumerable<GroupGoal>, IEnumerable<GroupGoalViewModel>>(groupGoalService.GetGroupGoals(id));

            foreach (var item in group.Goals)
            {
                var user = userService.GetUser(item.GroupUser.UserId);

                item.UserId = user.Id;
                item.User = user;
            }
            var assignedgroupuser = groupUserService.GetGroupUser(User.Identity.GetUserId(), id);
            if (assignedgroupuser != null)
            {
                group.GoalsAssignedToOthers = Mapper.Map<IEnumerable<GroupGoal>, IEnumerable<GroupGoalViewModel>>(groupGoalService.GetAssignedGoalsToOthers(assignedgroupuser.GroupUserId));
                group.GoalsAssignedToMe = Mapper.Map<IEnumerable<GroupGoal>, IEnumerable<GroupGoalViewModel>>(groupGoalService.GetAssignedGoalsToMe(assignedgroupuser.GroupUserId));
            }
            group.Focus = focusService.GetFocussOFGroup(id);

            //group.GroupUserId = groupUserService.GetGroupUserByuserId(((SocialGoalUser)(User.Identity)).UserId).GroupUserId;
            group.Users = groupUserService.GetMembersOfGroup(id);
            //if (group.GroupUser.UserId == ((SocialGoalUser)(User.Identity)).UserId)
            if (groupUserService.GetAdminId(id) == User.Identity.GetUserId())
                group.Admin = true;
            var status = 0;
            foreach (var item in group.Users)
            {
                if (item.Id == (User.Identity.GetUserId()))
                    status = 1;
            }
            if (status == 1)
                group.IsAMember = true;
            if (groupRequestService.RequestSent((User.Identity.GetUserId()), id))
                group.RequestSent = true;
            if (groupInvitationService.IsUserInvited(id, (User.Identity.GetUserId())))
                group.InvitationSent = true;
            return View("Index", group);
        }

        public ViewResult MyGroups()
        {
            var groupids = groupUserService.GetGroupAdminUsers(User.Identity.GetUserId());
            var allGroups = groupService.GetGroups(groupids);
            return View(allGroups);
        }

        public ViewResult Following()
        {
            var groupids = groupUserService.GetFollowedGroups(User.Identity.GetUserId());
            var allGroups = groupService.GetGroups(groupids);
            return View(allGroups);
        }

        public ViewResult JoinedUsers(int id)
        {
            var members = groupUserService.GetMembersOfGroup(id);
            GroupMemberViewModel gmvm = new GroupMemberViewModel() { GroupId = id, Group = groupService.GetGroup(id), Users = members };
            return View(gmvm);
        }

        //
        // GET: /Group/Create
        public PartialViewResult CreateGroup()
        {
            var groupFormViewModel = new GroupFormModel();
            return PartialView(groupFormViewModel);
        }

        public ViewResult ShowAllRequests(int id)
        {
            var groupRequests = groupRequestService.GetGroupRequests(id);
            var groupRequestViewModel = Mapper.Map<IEnumerable<GroupRequest>, IEnumerable<GroupRequestViewModel>>(groupRequests);
            ViewBag.CurrentGroupID = id;
            return View("_RequestsView", groupRequestViewModel);
        }

        public ViewResult Members(int id)
        {
            var members = groupUserService.GetMembersOfGroup(id);
            GroupMemberViewModel gmvm = new GroupMemberViewModel() { GroupId = id, Group = groupService.GetGroup(id), Users = members };
            return View(gmvm);
        }

        public ActionResult DeleteMember(string userId, int groupId)
        {
            var membertodelete = groupUserService.GetGroupUser(userId, groupId);
            groupUserService.DeleteGroupUser(membertodelete.GroupUserId);
            return RedirectToAction("Index", new { id = membertodelete.GroupId });
        }

        //
        // POST: /Group/Create

        [HttpPost]
        public ActionResult CreateGroup(GroupFormModel newGroup)
        {
            var userId = User.Identity.GetUserId();
            Group group = Mapper.Map<GroupFormModel, Group>(newGroup);
            var errors = groupService.CanAddGroup(group).ToList();
            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                //group.UserId = ((SocialGoalUser)(User.Identity)).UserId;
                var createdGroup = groupService.CreateGroup(group, userId);
                //var createdGroup = groupService.GetGroup(newGroup.GroupName);
                //var groupAdmin = new GroupUser { GroupId = createdGroup.GroupId, UserId = ((SocialGoalUser)(User.Identity)).UserId, Admin = true };
                //groupUserService.CreateGroupUser(groupAdmin, groupInvitationService);
                return RedirectToAction("Index", new { id = createdGroup.GroupId });
            }
            return View("CreateGroup", newGroup);
        }

        //
        // GET: /Group/Edit
        public ActionResult EditGroup(int id)
        {
            var group = groupService.GetGroup(id);
            GroupFormModel editGroup = Mapper.Map<Group, GroupFormModel>(group);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View("_EditGroup", editGroup);
        }

        public ViewResult CreateFocus(int id)
        {
            return View(new FocusFormModel() { GroupId = id, Group = groupService.GetGroup(id) });
        }

        [HttpPost]
        public ActionResult CreateFocus(FocusFormModel focus)
        {
            var errors = focusService.CanAddFocus(Mapper.Map<FocusFormModel, Focus>(focus)).ToList();

            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                Focus newFocus = Mapper.Map<FocusFormModel, Focus>(focus);
                focusService.CreateFocus(newFocus);
                //var createdfocus = focusService.GetFocus(focus.FocusName);
                return RedirectToAction("Focus", new { id = newFocus.FocusId });
            }
            return View("CreateFocus", focus);
        }

        public ActionResult Focus(int id)
        {
            FocusViewModel Focus = Mapper.Map<Focus, FocusViewModel>(focusService.GetFocus(id));

SocialGoal/Views/Group/CreateGoal.cshtml
@model SocialGoal.Web.ViewModels.GroupGoalFormModel
@{
    ViewBag.Title = "Create Goal";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}
@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>*@
<div class="well span10">
    <h4>
        Create Group Goal
    </h4>
    @Html.Partial("Header")
    <br />
    <div id="createGoal" class="well span8">
        @using (Html.BeginForm("CreateGoal", "Group"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.GroupId)

            @Html.ValidationSummary(true)
            <table class="table ">
                <tr>
                    <td class="span12">
                        @Html.TextBoxFor(model => model.GoalName, new { placeholder = "Enter The Goal Name" })
                        @Html.ValidationMessageFor(model => model.GoalName)
                    </td>
                </tr>
                <tr>
                    <td class="">
                        @Html.TextBoxFor(model => model.Description, new { placeholder = "Enter The Description" })
                        @Html.ValidationMessageFor(model => model.Description)
                    </td>
                </tr>
                <tr>
                    <td class="">
                        @Html.TextBoxFor(model => model.StartDate, new { @class = "ui-datepicker", @readonly = "readonly", @style = "display:block;float:left", placeholder = "StartDate Of the Goal" })
                        @Html.ValidationMessageFor(model => model.StartDate)
                    </td>
                </tr>
                <tr>
                    <td class="">
                        @Html.TextBoxFor(model => model.EndDate, new { @class = "ui-datepicker", @readonly = "readonly", @style = "display:block;float:left", placeholder = "EndDate Of the Goal" })
                        @Html.ValidationMessageFor(model => model.EndDate)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DropDownListFor(model => model.FocusId, Model.Foci, "--Select Focus--")
                        @Html.ValidationMessageFor(model => model.FocusId)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DropDownListFor(model => model.MetricId, Model.Metrics, "--Select Metric--")
                        @Html.ValidationMessageFor(model => model.MetricId)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.TextBoxFor(model => model.Target, new { placeholder = "Enter the Target to be Achieved" })
                        @Html.ValidationMessageFor(model => model.Target)
                         <a href="#"  id="targetinfo" rel ="popover" data-content= "Fix the target of the goal based on metric selected. It should be a numeric. eg:100" data-trigger ="hover" data-placement="top" data-originals-title ="Target"><i class="icon-info-sign"></i> </a>
                    </td>
                </tr>
                <tr>
                  
                    <td>@Html.TextBoxFor(model => model.AssignedTo, new { id = "AssignedUser", value = "", placeholder = "Assigned To", @readonly = "readonly" })
                 <a href="#"  id="assigngoalsinfo" rel ="popover" data-content= "You can seach the user by clicking on the search button and assign the current goal for him. " data-trigger ="hover" data-placement="top" data-originals-title ="Assign Goals"><i class="icon-info-sign"></i> </a>
                    </td>
                    <td>
                        <a data-toggle="modal" href="#searchMember" onclick="SearchMember('@Model.GroupId');" class="btn btn-primary" title ="You can assign Goals to the members of the group">Search
                        </a>  
                    </td>
                      <td><input type ="button" id "removeassignedto" class ="btn" value="Remove" onclick ="RemoveAssigned()"  title ="You can remove the Assigned Users"/></td>
                    <td>
                    @Html.HiddenFor(m => m.AssignedGroupUserId, new { @id = "assignedgroupuserId" })
                    @*<input type= "hidden" value = "abc" id ="assignedgroupuserId" />*@</td>
                </tr>
            </table>
            <p>
                <button class="btn btn-primary" type="submit" value="Create">
                    Create</button>
                <button class="btn" type ="reset" value="Cancel" onclick="window.location.href='@Url.Action("Index", "Group", new { @id = Model.GroupId })'">
                    Cancel</button></p>
               

        }
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        $('.ui-datepicker').each(function (i, v) {
            $(v).datepicker({
                dateFormat: 'dd-M-yy',
                buttonImage: '@Url.Content("~/Content/calendar.gif")',
                buttonImageOnly: true,
                showOn: "button"
            });
        });
    });

    $(function () {
        $("#assigngoalsinfo").popover();
    });
    $(function () {
        $("#targetinfo").popover();
    });
</script>

SocialGoal/Views/Group/DeleteFocus.cshtml
@model SocialGoal.Model.Models.Focus

@{
    ViewBag.Title = "DeleteFocus";
}

<div class ="alert alert-block alert-error fade in">
<strong>Delete Focus</strong>
<br />
     Are you sure you want to delete this?
     <br />
     <br />
   
<table>
            <tr>
                <td >
                    @Html.DisplayNameFor(model => model.FocusName)
                </td>
                <td >
                    @Html.DisplayFor(model => model.FocusName)
                   
                </td>
            </tr>
            <tr>
                <td >
                    @Html.DisplayNameFor(model => model.Description)
                </td>
                <td >
                    @Html.DisplayFor(model => model.Description)
                </td>
            </tr>
            </table>
            <br />
              <p>
            

        @using (Html.BeginForm())
{
            @Html.AntiForgeryToken()
    <p>
      

             <button class="btn btn-danger" type="submit"  value="Submit"> Delete</button>
             <button class="btn" value="Cancel"  type ="reset" onclick="window.location.href='@Url.Action("Index", "Group", new { id = Model.GroupId})'">
        Cancel</button>
        
    </p>
      
     
 
 

}
 
</div>

SocialGoal/Views/Group/EditGoal.cshtml
@model SocialGoal.Web.ViewModels.GroupGoalFormModel
@{
    ViewBag.Title = "Create Goal";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}
@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>*@



<div class="span12 well">
    <div class="span6" style="margin-left:10px;">
        <h4>@Html.ActionLink(@Model.Group.GroupName, "Index", new { id = @Model.GroupId })</h4>
        <div><small>@Model.Group.Description</small></div>
    </div>

    <div class="span5" style="margin-left:90px;" >
        @Html.Partial("Header")
    </div>
</div>

<div id="createGoal" class="span12 well" style="margin:0px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.GroupId)

        @Html.ValidationSummary(true)

        <table class ="table">
            <tr>
                <td>Goal Name</td>
                <td >
                    @Html.TextBoxFor(model => model.GoalName, new { @class ="span11" })
                    @Html.ValidationMessageFor(model => model.GoalName)
                </td>
            </tr>
            <tr>
                <td>
                    Description
                </td>
                <td >
                    @Html.TextAreaFor(model => model.Description, new { @class ="span11" })
                    @Html.ValidationMessageFor(model => model.Description)
                </td>
            </tr>
            <tr>
                <td>
                   Start Date
                </td>
                <td >
                    @Html.TextBoxFor(model => model.StartDate, String.Format("{0:dd-MMM-yyyy}", Model.StartDate), new { @class = "ui-datepicker span11", @readonly = "readonly", @style = "display:block;width:150;float:left;margin-right:7px;" })
                    @Html.ValidationMessageFor(model => model.StartDate)
                </td>
            </tr>
            <tr>
                <td>
                   End Date
                </td>
                <td >
                    @Html.TextBoxFor(model => model.EndDate,String.Format("{0:dd-MMM-yyyy}",Model.EndDate), new { @class = "ui-datepicker span11", @readonly = "readonly", @style = "display:block;width:150;float:left;margin-right:7px;" })
                   @Html.ValidationMessageFor(model => model.EndDate)
                </td>
            </tr>
            <tr>
                <td>
                   Goal Metric
                </td>
                <td >
                     @Html.DropDownListFor(model => model.MetricId, Model.Metrics, "--Select--", new { @class = "span11" })
                    @Html.ValidationMessageFor(model => model.MetricId)
                </td>
            </tr>
            <tr>
                <td>
                    Focus
                </td>
                <td >
                    @Html.DropDownListFor(model => model.FocusId, Model.Foci, "--Select--", new { @class = "span11" })
                    @Html.ValidationMessageFor(model => model.FocusId)
                </td>
                <td>
                    @Html.Hidden("UserId", User.Identity.GetUserId())
                    
                    @Html.HiddenFor(m=>m.GroupGoalId)
                    @Html.HiddenFor(m=>m.GroupUserId)
                </td>
            </tr>
            
            
            <tr>
                <td>
                Target
                </td>
                <td >
                    @Html.TextBoxFor(model => model.Target, new { @class = "span11" })
                    @Html.ValidationMessageFor(model => model.Target)
                    <a href="#"  id="targetinfo" rel ="popover" data-content= "Fix the target of the goal based on metric selected" data-trigger ="hover" data-placement="top" data-originals-title ="Target"><i class="icon-info-sign"></i> </a>
                </td>
            </tr>

              <tr>
                  <td>Assigned To</td>
                  <td>
                        @Html.TextBoxFor(model => model.AssignedTo, new { id = "AssignedUser", value = "", placeholder = "Assigned To", @readonly = "readonly",@class="span8" })
                        <a href="#"  id="assigngoalsinfo" rel ="popover" data-content= "You can seach the user by clicking on the search button and assign the current goal for him. " data-trigger ="hover" data-placement="top" data-originals-title ="Assign Goals">
                            <i class="icon-info-sign"></i> 
                        </a>
                        <a data-toggle="modal" href="#searchMember" onclick="SearchMember('@Model.GroupId');" class="btn btn-primary" title ="You can assign Goals to the members of the group">Search </a>  
                        <a data-toggle="modal" id= "removeassignedto" href="#" onclick="RemoveAssigned()" class="btn" title ="You can remove the assigned user">Remove </a>                          
                        @Html.HiddenFor(m => m.AssignedGroupUserId, new { @id = "assignedgroupuserId" })
                  </td>
                </tr>
                <tr>
                <td colspan="2">
                             <p>
                       <button class="btn btn-primary" type="submit" value="Save" >
                        Save</button>
                           <button class="btn" type ="reset" value="Cancel" onclick="window.location.href='@Url.Action("GroupGoal", "Group", new { id = Model.GroupGoalId })'">
                    Cancel</button>
                    </p>
                </td>
                </tr>
        </table>
       
      

    }
    
</div>
@*<style type="text/css">
    input, button
    {
        border-radius: 5px;
    }
    select
    {
       @* width: 155px;
        height: 22px;
        background-color: white;
        @*border: 2px inset;
        border-radius: 5px;
    }
</style>*@
<script type="text/javascript">
    $(document).ready(function () {

        //        $('.ui-datepicker').datepicker({
        //            dateFormat: 'mm/dd/yy',
        //            buttonImage: '@Url.Content("~/Content/calendar.gif")',
        //            buttonImageOnly: true,
        //            showOn: "button"
        //        });
        $('.ui-datepicker').each(function (i, v) {
           // $(v).val($.datepicker.formatDate('dd-M-yy', new Date($(v).val())))
            $(v).datepicker({
                dateFormat: 'dd-M-yy',
                buttonImage: '@Url.Content("~/Content/calendar.gif")',
                buttonImageOnly: true,
                showOn: "button"
            });
        });
    });

    $(function () {
        $("#targetinfo").popover();
    });
    $(function () {
        $("#assigngoalsinfo").popover();
    });
</script>

SocialGoal/Views/Group/ListOfGroups.cshtml
@model GroupsPageViewModel
@{
    ViewBag.Title = "ListOfGroups";
}

<div class="well span12">
    
    <div class="span7" style="padding-left:30px;"><h4>Groups</h4></div>

    <div class="span5" style="padding-left:38px;">
        <strong>Filter By</strong>         
        @Html.EnumDropDownListFor(model => model.Filter, new { @onchange = "LoadGroups();" })
    </div>
    
    @*This is the container that will be replaced by all ajax requests from either paging or changing the filter*@
    <div id="GroupPagingContainer" class="span11" style="margin-top: 10px;">
        @Html.Partial("_GroupsTable", Model)
    </div>
    
</div>

<script type="text/javascript">
    function LoadGroups() {
        var url = "@Url.Action("GroupList","Group")" + "?filter=" + $('#Filter').val();
        $.get(url).done(function(html) {
             $("#GroupPagingContainer").html(html);
        });
    }
</script>