SocialGoal/Controllers/GoalController.cs
using AutoMapper;
using SocialGoal.Model.Models;
using SocialGoal.Service;
using SocialGoal.Web.Core.Models;
using SocialGoal.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialGoal.Web.Core.Extensions;
using SocialGoal.Web.Mailers;
using SocialGoal.Properties;
using Microsoft.AspNet.Identity;

namespace SocialGoal.Web.Controllers
{
    [Authorize]
    public class GoalController : Controller
    {
        private readonly IGoalService goalService;
        private readonly IMetricService metricService;
        private readonly IFocusService focusService;
        private readonly ISupportService supportService;
        private readonly IUpdateService updateService;
        private readonly ICommentService commentService;
        private readonly IUserService userService;
        public readonly ISecurityTokenService securityTokenService;
        public readonly ISupportInvitationService supportInvitationService;
        private readonly IGoalStatusService goalStatusService;
        private readonly ICommentUserService commentUserService;
        private readonly IUpdateSupportService updateSupportService;

        private IUserMailer userMailer = new UserMailer();
        public IUserMailer UserMailer
        {
            get { return userMailer; }
            set { userMailer = value; }
        }

        public GoalController(IGoalService goalService, IMetricService metricService, IFocusService focusService, ISupportService supportService, IUpdateService updateService, ICommentService commentService, IUserService userService, ISecurityTokenService securityTokenService, ISupportInvitationService supportInvitationService, IGoalStatusService goalStatusService, ICommentUserService commentUserService, IUpdateSupportService updateSupportService)
        {
            this.goalService = goalService;
            this.supportInvitationService = supportInvitationService;
            this.metricService = metricService;
            this.focusService = focusService;
            this.supportService = supportService;
            this.updateService = updateService;
            this.commentService = commentService;
            this.userService = userService;
            this.securityTokenService = securityTokenService;
            this.goalStatusService = goalStatusService;
            this.commentUserService = commentUserService;
            this.updateSupportService = updateSupportService;
        }

        public ActionResult Index(int id)
        {
            var goal = goalService.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            var goalDetails = Mapper.Map<Goal, GoalViewModel>(goal);
            goalDetails.Supported = supportService.IsGoalSupported(id, User.Identity.GetUserId());
            var goalstatus = goalStatusService.GetGoalStatus();
            goalDetails.GoalStatuses = goalstatus.ToSelectListItems(goal.GoalStatusId);
            return View(goalDetails);
        }

        public ViewResult MyGoal()
        {
            string userid = User.Identity.GetUserId();
            var Goals = goalService.GetMyGoals(userid);
            var goalDetails = Mapper.Map<IEnumerable<Goal>, IEnumerable<GoalViewModel>>(Goals);
            return View(goalDetails);
        }

        public ViewResult FollowedGoal()
        {
            var followed = supportService.GetUserSupportedGoals(User.Identity.GetUserId(), goalService);
            return View(followed);
        }

        public PartialViewResult Create()
        {
            var createGoal = new GoalFormModel();
            var metrics = metricService.GetMetrics();
            var goalstatus = goalStatusService.GetGoalStatus();
            createGoal.Metrics = metrics.ToSelectListItems(-1);
            return PartialView(createGoal);
        }

        [HttpPost]
        public ActionResult Create(GoalFormModel createGoal)
        {
            Goal goal = Mapper.Map<GoalFormModel, Goal>(createGoal);
            var errors = goalService.CanAddGoal(goal, updateService).ToList();
            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                goalService.CreateGoal(goal);
                return RedirectToAction("Index", new { id = goal.GoalId });
            }
            var metrics = metricService.GetMetrics();
            var goalstatuss = goalStatusService.GetGoalStatus();
            createGoal.Metrics = metrics.ToSelectListItems(-1);
            return View("Create", createGoal);
        }

        public ActionResult Edit(int id)
        {
            var goal = goalService.GetGoal(id);
            GoalFormModel editGoal = Mapper.Map<Goal, GoalFormModel>(goal);
            if (goal == null)
            {
                return HttpNotFound();
            }
            var metrics = metricService.GetMetrics();
            if (goal.Metric != null)
                editGoal.Metrics = metrics.ToSelectListItems(goal.Metric.MetricId);
            else
                editGoal.Metrics = metrics.ToSelectListItems(-1);
            return View(editGoal);
        }

        [HttpPost]
        public ActionResult Edit(GoalFormModel editGoal)
        {
            Goal goalToEdit = Mapper.Map<GoalFormModel, Goal>(editGoal);
            var errors = goalService.CanAddGoal(goalToEdit, updateService);
            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                goalService.EditGoal(goalToEdit);
                return RedirectToAction("Index", new { id = editGoal.GoalId });
            }
            else
            {
                var metrics = metricService.GetMetrics();
                var goalstatus = goalStatusService.GetGoalStatus();
                var goal = goalService.GetGoal(editGoal.GoalId);
                if (goal.Metric != null)
                    editGoal.Metrics = metrics.ToSelectListItems(goal.Metric.MetricId);
                else
                    editGoal.Metrics = metrics.ToSelectListItems(-1);

                return View(editGoal);
            }
        }

        [HttpPost]
        public string GoalStatus(int id, int goalid)
        {
            var goal = goalService.GetGoal(goalid);
            goal.GoalStatusId = id;
            goalService.SaveGoal();
            string msg = goal.GoalStatus.GoalStatusType;
            return msg;
        }

        public ActionResult Delete(int id)
        {
            var goal = goalService.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            return View(goal);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var goal = goalService.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }

            goalService.DeleteGoal(id);
            return RedirectToAction("Index", "Home");
        }

        public PartialViewResult MyGoals()
        {
            string userid = User.Identity.GetUserId();
            var Goals = goalService.GetMyGoals(userid);
            return PartialView("_MyGoalsView", Goals);
        }

        public PartialViewResult GoalsFollowing()
        {
            var followed = supportService.GetUserSupportedGoals(User.Identity.GetUserId(), goalService);
            return PartialView("_FollowedGoals", followed);
        }

        public PartialViewResult DisplayUpdates(int id)
        {
            var Updates = Mapper.Map<IEnumerable<Update>, IEnumerable<UpdateViewModel>>(updateService.GetUpdatesByGoal(id));
            foreach (var item in Updates)
            {
                item.IsSupported = updateSupportService.IsUpdateSupported(item.UpdateId, User.Identity.GetUserId());
            }
            UpdateListViewModel updates = new UpdateListViewModel()
            {

                Updates = Updates,
                Metric = goalService.GetGoal(id).Metric,
                Target = goalService.GetGoal(id).Target,
                // IsSupported =  updateSupportService.IsUpdateSupported(,((SocialGoalUser)(User.Identity)).UserId)
            };
            return PartialView("_UpdateView", updates);
        }

        public ViewResult Supporters(int id)
        {
            var members = supportService.GetSupportersOfGoal(id, userService);
            GoalSupporterViewModel gsvm = new GoalSupporterViewModel() { GoalId = id, Goal = goalService.GetGoal(id), Users = members };
            return View(gsvm);
        }

        [HttpPost]
        public ActionResult SaveUpdate(UpdateFormModel newupdate)
        {
            // Update update = Mapper.Map<UpdateFormModel, Update>(newupdate);
            if (ModelState.IsValid)
            {
                Update update = Mapper.Map<UpdateFormModel, Update>(newupdate);
                update.Goal = goalService.GetGoal(newupdate.GoalId);
                var updateVal = updateService.GetHighestUpdateValue(newupdate.GoalId);
               
                if(updateVal!=null)
                {  
                    if (updateVal.status <= newupdate.status)
                    {
                        updateService.CreateUpdate(update);
                       
                    }
                    else
                    {
                        update.status = -1;
                        ModelState.AddModelError(update.Updatemsg, "cannot enter");
                    }
                }
                else
                {
                    updateService.CreateUpdate(update);
                }


                     var Updates = Mapper.Map<IEnumerable<Update>, IEnumerable<UpdateViewModel>>(updateService.GetUpdatesByGoal(newupdate.GoalId));
                     foreach (var item in Updates)
                     {

SocialGoal/Views/Shared/_AlertInfo.cshtml
@model string
<div class="alert alert-info">
    @Model
</div>

SocialGoal/Views/Shared/_Header.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span
        class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
    </a>
    <a class="brand" href='@Url.Action("Index", "Home")'>Social Goal</a>
    <div class="btn-group pull-right">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-user">
        </i>
            @{
    var name = User.Identity.Name;
                <text> @name </text>
            }
            <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("Profile", "UserProfile", "Account", new { id = User.Identity.GetUserId() }, new { @title = "View Profile" })
            </li>
            <li class="divider"></li>
            @*<li><a href="/Account/LogOff">Sign Out</a></li>*@
            <li>@Html.ActionLink("Sign Out","LogOff","Account")</li>
        </ul>
    </div>
    
    <div class="nav-collapse">
        <ul class="nav">
            <li><a href="/Home/Index">Home</a></li>
            <li><a href="/Notification/Index">My Invitations
                @{
    var not = Html.Action("GetNumberOfInvitations", "Notification");
    if (not.ToString() != "0")
    { 
                    <sup><span class="badge badge-important">@not</span> </sup>
    }
                }
            </a></li>
            @*<li><a href="/Goal/ListOfGoals">Goals</a></li>*@
            <li><a href="/Goal/GoalList">Goals</a></li>
            @*<li><a href="/Group/ListOfGroups">Groups</a></li>*@
            <li><a href="/Group/GroupList">Groups</a></li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">People
                <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class=""><a href="/Account/Followers">Followers</a></li>@*onclick="GetFollowers();"*@
                    <li class=""><a href="/Account/Followings">Following</a> </li>
                </ul>
            </li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Create
                <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class=""><a data-toggle="modal" href="#creategoal" onclick="CreateGoal();">Create
                        Goal</a></li>
                    <li class=""><a data-toggle="modal" href="#creategroup" onclick="CreateGroup();">Create
                        Group</a> </li>
                </ul>
            </li>
            <li>
                <form action="/Search/SearchAll" class="navbar-search" id="searchform" method="post">
                <input class="search-query span2" id="searchText" name="searchText" placeholder="Search"  type="text" value="@ViewBag.searchtext" />
                <input type="submit" style="display: none;" />
                </form>
            </li>
        </ul>
    </div>
    
}

<link href="/Content/CustomStyles.css" rel="stylesheet" type="text/css" />
<script type="text/javascript">
    $(document).ready(function () {
        $(".nav-collapse .nav li a").click(function (e) {
            $(".nav-collapse .nav .active").removeClass("active")
            $(this).parent().addClass("active")
        });
    });

    $('#searchText').keypress(function (e) {
        var code = (e.keyCode ? e.keyCode : e.which);
        if (code == 13 && $(this).val() != "") {
            $('#searchform').submit();
        }

    });

</script>

SocialGoal/Views/Shared/_HomeLayout.cshtml
@model dynamic
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Social Goal</title>
    
     @Styles.Render("~/Content/CSS")
	 @Scripts.Render("~/Scripts/HomeLayout")
    
</head>
<body>
    <div class="navbar navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <section id="login">
                    @Html.Partial("_Header")
                </section>
            </div>
        </div>
    </div>
    <div class="container-fluid margin-top">
        <div class="row-fluid" style="margin-top: 10px;">
            <div class="prettyprint linenums" id="content">
                @RenderBody()
            </div>
            @*<div class="span3">
					<div class="row-fluid">
						<div id="mygoals" class="well">
							<h5>
								MY GOALS</h5>
							<div>
								@{ Html.RenderAction("MyGoals", "Goal"); }
							</div>
						</div>
						<div id="followedgoals" class="well">
							<h5 title="user following goals">
								FOLLOWED GOALS</h5>
							<div>
								@{ Html.RenderAction("GoalsFollowing", "Goal"); }
							</div>
						</div>
					</div>
				</div>
				<div class="span3">
					<div class="row-fluid">
						<div id="mygroup" class="well">
							<h5>
								MY GROUPS</h5>
							<div id="divCreateGroup" style="display: none">
							</div>
							<div>
								@{ Html.RenderAction("GroupsView", "Group"); }
							</div>
						</div>
						<div id="followedgroups" class="well">
							<div>
								<h5>
									FOLLOWED GROUPS</h5>
								<div>
									@{ Html.RenderAction("FollowedGroups", "Group"); }
								</div>
							</div>
						</div>
					</div>
				</div>*@
            <!-- end .sidebar2 -->
        </div>
    </div>
    <!---for modal popup -->
    <div class="modal" id="creategoal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        style="display: none;" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="enableScroll()">
                ×</button>
            <h5 id="myModalLabel">
                Create Goal</h5>
        </div>
        <div class="modal-body" id="createGoal">
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true" onclick="enableScroll()">
                Close</button>
        </div>
    </div>
    <div class="modal" id="creategroup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        style="display: none;" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="enableScroll()">
                ×</button>
            <h5 id="myModalLabel">
                Create Group</h5>
        </div>
        <div class="modal-body" id="createGroup">
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true" onclick="enableScroll()">
                Close</button>
        </div>
    </div>
    <div class="modal" id="follower" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        style="display: none;" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="enableScroll()">
                ×</button>
            <h5 id="myModalLabel">
                Followers</h5>
        </div>
        <div class="modal-body" id="followedUsers">
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true" onclick="enableScroll()">
                Close</button>
        </div>
    </div>
    <div class="modal" id="following" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        style="display: none;" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="enableScroll()">
                ×</button>
            <h5 id="myModalLabel">
                Followings</h5>
        </div>
        <div class="modal-body" id="followingUsers">
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true" onclick="enableScroll()">
                Close</button>
        </div>
    </div>
    <!--ends here---------->
</body>
</html>
<style type="text/css">
.thumbnail
{
width:50px;
height:40px;
}
</style>
<script type="text/javascript">
function search(e) {
window.event.preventDefault();

			var goal = $("#goal").val();
			window.location = '/Search/SearchAll/'+goal;

	}
$(function(){
	$('#follower').niceScroll();
    $('.tab-content').niceScroll();
});
$(function(){
	$('#following').niceScroll();
});

$(function(){
	$('#divFollowedGroup').niceScroll();
});

$(function(){
	$('#divGroup').niceScroll();
});
$(function(){
	$('#divSGoals').niceScroll();
});
$(function(){
	$('#divGoals').niceScroll();
});
$(function(){
	$('#notification').niceScroll();
});


	function GetFollowers()
{
$('#divFollowedGroup').getNiceScroll().remove();
$('#divSGoals').getNiceScroll().remove();
$('#divGoals').getNiceScroll().remove();
$('#notification').getNiceScroll().remove();
 var url ="/Account/Followers";
 $.get(url,function(result){
	$("#followedUsers").html(result);

 });
}

function GetFollowings()
{
$('#divFollowedGroup').getNiceScroll().remove();
$('#divSGoals').getNiceScroll().remove();
$('#divGoals').getNiceScroll().remove();
$('#notification').getNiceScroll().remove();
 var url ="/Account/Followings";
 $.get(url,function(result){
	$("#followingUsers").html(result);

 });
}


function CreateGoal()
{
$('#divFollowedGroup').getNiceScroll().remove();
$('#divSGoals').getNiceScroll().remove();
$('#divGoals').getNiceScroll().remove();
$('#notification').getNiceScroll().remove();
 var url ="/Goal/Create";
 $.get(url,function(result){
	$("#createGoal").html(result);

 });
}

function DeleteUser(userId,groupId) {
	

        $.get("/Group/DeleteMember",{'userId':userId,'groupId':groupId}, function (e) {
			$("#" + userId).html(e);
			$("#divFollowedGroup").load("/Group/FollowedGroups");
		});
	}


	function CreateGroup()
	{
	$('#divFollowedGroup').getNiceScroll().remove();
	$('#divSGoals').getNiceScroll().remove();
	$('#divGoals').getNiceScroll().remove();
	$('#notification').getNiceScroll().remove();
	var url ="/Group/CreateGroup";
	$.get(url,function(result){
	$("#createGroup").html(result);
	$('#notification').getNiceScroll();
 });
}
		function toggleDiv(divId){
			$(eval(divId)).toggle("slow");
		}
	function onBegin_CreateGoal(ajaxContext) {
		var jsonObject = eval(ajaxContext);
		$("#divCreateGoal").toggle();
	}

	function enableScroll()
	{
		$('#divFollowedGroup').niceScroll();
		$('#divGroup').niceScroll();
		$('#divSGoals').niceScroll();
		$('#divGoals').niceScroll();
		$('#notification').niceScroll();

	}
function GroupEdit(GroupId) {
	var url = '/Group/EditGroup';
	$('#EditpreviewLayergroup').jqm().jqDrag('#handleGroup');
	$.get(url, { 'id': GroupId}, function (result) {

		$('#EditpreviewContentgroup').empty().append(result); //empty previewContent and add the generated preview
		$('#EditpreviewLayergroup').jqmShow(); //show previewLayer

	});
}

function EditGroup(id,userid) {
	var url = '/Group/EditGroup';
	var GroupName = $("#GroupName").val();
	var Description = $("#Description").val();

	var PostData = { 'GroupId': id, 'GroupName': GroupName, 'Description': Description, 'UserId': userid  };
	$.post(url, PostData, function (result) {
	$("#divEditGroup" + id.toString()).html(result);
		$('#EditpreviewLayergroup').jqmHide();
	});
}

function GroupDelete(GroupId) {
	var url = '/Group/DeleteGroup';
	$('#DeletepreviewLayergroup').jqm().jqDrag('#handleGroup');
	$.get(url, { 'id': GroupId }, function (result) {

		$('#DeletetpreviewContentgroup').empty().append(result); //empty previewContent and add the generated preview
		$('#DeletepreviewLayergroup').jqmShow(); //show previewLayer

	});
}

function DeleteGrpConfirmed(id) {
	var GoalId = id;
	var url = '/Group/DeleteGroup';
	var postdata = { 'id': id }
	$.post(url, postdata, function (result) {
		$("#divDeleteGroup" + id.toString()).html(result);
		$('#DeletepreviewLayergroup').jqmHide();
	});
}

function selectUser(userName, groupId) {
	var postData = { 'GroupId': groupId, 'Email': userName, 'Admin': false };
	var url = '/MyGroup/AddNewUser';
	$.post(url, postData, function (result) {
		$("#divUsers").html(result);
	});
}
function editGet(id) {
	var GoalId = id;
	var url = '/Goal/Edit';
	$.get(url, { 'GoalId': GoalId }, function (result) {
	});

}

function DeleteGet(id) {
	var GoalId = id;
	var url = '/Goal/Delete';
	
	$.get(url, { 'GoalId': GoalId }, function (result) {
	});

}

function editSave(id) {
	 var GoalName = $("#GoalName").val();
	 var Desc = $("#Desc").val();
	 var StartDate = $("#StartDate" ).val();
	 var EndDate = $("#EndDate" ).val();
	 var GoalMetric = $("#MetricId" ).val()  ;
	 var Target = $("#Target" ).val();
	 var GoalType = $("#GoalType").val();
	 var user = $("#UserId").val();
	 var PostData = { 'GoalId': id, 'GoalName': GoalName,'Desc' : Desc, 'StartDate': StartDate, 'EndDate': EndDate, ' MetricId': GoalMetric ,'Target': Target, 'GoalType': GoalType, 'UserId': user };

	 $.ajax({
		type:post,
		 url: "/Goal/Edit",
		 data: PostData,
	 }).done(function (result) {
		 $(this).addClass("done");
		  $("#divEdit" + id.toString()).html(result);
	 });

 }


 function saveUpdate() {
		var update = 'Please Enter Update';
		var data = 'Please Enter Status';
		var Gid = $('#GoalId').val();
		var CurrUpdte = $('#Update').val();
		var CurrStatus = $('#Status').val();

		if ( ($('#Status').val() == '')) {
			alert(data);
		}

		else
			if ($('#Update').val() == '') {
				alert(update);
			}
			else {

				var PostData = { 'GoalId': Gid, 'Updatemsg': CurrUpdte, 'status': CurrStatus };
				var url = '/MyGoals/SaveUpdate';
				$.post(url, PostData, function (response) {


					$("#divupdate").html(response);
					$("#Update").val('');
					$("#Status").val('');
				}
	   );
			}
	}

	function saveGroupUpdate() {
	var update = 'Please Enter Update';
	$("#postupdate").attr("disabled", "true");

	var Gid = $('#GoalId').val();
	var CurrUpdte = $('#Update').val();
	var CurrStatus = $('#Status').val();

	if ($('#Update').val() == '') {
		alert(update);
		$("#postupdate").removeAttr("disabled");
	}
	else {
		var PostData = { 'GoalId': Gid, 'Updatemsg': CurrUpdte, 'status': CurrStatus };
		var url = '/Goal/SaveUpdate';
		$.post(url, PostData, function (response) {
			$("#divupdate").html(response);
			$("#Update").val('');
			$("#Status").val('');
			$("#postupdate").removeAttr("disabled");

		});
	}
}

	 function isNumberKey(evt) {
		var charCode = (evt.which) ? evt.which : event.keyCode
		if (charCode > 31 && (charCode < 48 || charCode > 57))
		  alert('Please Enter Integers');
	}

	function userslist(id)
	{
	 var url = '/MyGroup/UsersList';
	 $('#userspreviewLayer').jqm().jqDrag('#handleusers');
	$.get(url, { 'GroupId': id }, function (result) {

		$('#userspreviewContent').empty().append(result); //empty previewContent and add the generated preview
		$('#userspreviewLayer').jqmShow(); //show previewLayer

	});

	}

   
	 function UnSupportGoal(goalId) {
		$.get("/Goal/UnSupportGoal/" + goalId, function (e) {
			$("#support" + goalId).html('<a id="Support' + goalId + '" onclick="SupportGoal(' + goalId + ')"><i class="icon-plus"></i>Follow</a>');
			$("#divSGoals").load("/Goal/GoalsFollowing");
		});
	}

	function DateValidation()
	{
		var SDate = $("#StartDate").val();
		var EDate = $("#EndDate").val();

		var endDate = new Date(EDate);
		var startDate = new Date(SDate);

		if (SDate != '' && EDate != '' && startDate > endDate) {
			alert("Please ensure that the End Date is greater than or equal to the Start Date.");
			theForm.txtEnd.focus();
			return false;
		}
	}
</script>

SocialGoal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/CSS")
    @Scripts.Render("~/Scripts/Layout")

</head>
<body>
    @RenderBody()
</body>
</html>
<script type="text/javascript">
    
    function EnableBtn() {
        $("#forgotPasswordEmail").empty();
        $("#sendBtn").removeAttr("disabled");
    }
    
    function DisableBtn() {
        if ($("#forgotPasswordEmail").val() == "") {
            $("#sendBtn").attr("disabled", "disabled");
        }
    }

    function SentEmail() {
        if ($("#forgotPasswordEmail").val() != "") {

            $("#sendBtn").attr("disabled", "true");
            var email = $("#forgotPasswordEmail").val();
            var url = "/Account/ForgotPassword";
            var postData = { 'Email': email}
            $.post(url, postData, function (result) {
                $("#msgReset").css({ 'display': 'block' });
                $("#msgReset").text(result);
                $("#msgReset").fadeOut(5000);
                $("#forgotPasswordEmail").val('');
                $("#sendBtn").removeAttr("disabled");
            });
        }
    }

  
</script>